name: Justin Acker's Dev Blog
url: http://www.justinacker.com
description: Musings on technology, development and gaming by Justin Acker

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
